### ISSUE TITLE
v-headway-target VS v-headway-trigger ?

### ISSUE THREAD

**Issue by wwandreww** [l-portet/nuxt-headway#1]
Thank you for the great package that makes the integration so easy!

Just one question. In the readme I found:
![readme](https://user-images.githubusercontent.com/12819691/137630423-814a3699-f038-4910-8908-dd190d08b1e7.jpg)

Using the **v-headway-target** directive gives an error (in browser's console):
`Failed to resolve directive: headway-target`

However, it looks like the directive **v-headway-trigger** works perfectly.

Am I doing something wrong or the README file should be updated?

Thanks again for the package!

**Comment by l-portet** [comment]
Hey, glad you like the package!

Thanks for noticing it, it's misspelled. The README is updated :)
